[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.8"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[override]]
  name = "github.com/golang/protobuf"
  version = "1.2.0"

[prune]
  go-tests = true
  unused-packages = true